// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import AcctformController from './acctform_controller';
application.register('acctform', AcctformController);

import ApplicationController from './application_controller';
application.register('application', ApplicationController);

import AttachmentUploadController from './attachment_upload_controller';
application.register('attachment-upload', AttachmentUploadController);

import DropdownController from './dropdown_controller';
application.register('dropdown', DropdownController);

import HelloController from './hello_controller';
application.register('hello', HelloController);

import InlineEditController from './inline_edit_controller';
application.register('inline-edit', InlineEditController);

import NavController from './nav_controller';
application.register('nav', NavController);

import QuickReceiptController from './quick_receipt_controller';
application.register('quick-receipt', QuickReceiptController);

import QuickReceiptReviewController from './quick_receipt_review_controller';
application.register('quick-receipt-review', QuickReceiptReviewController);

import SharedController from './shared_controller';
application.register('shared', SharedController);

import StashlistController from './stashlist_controller';
application.register('stashlist', StashlistController);

import TransactionListController from './transaction_list_controller';
application.register('transaction-list', TransactionListController);

import TransactionReviewController from './transaction_review_controller';
application.register('transaction-review', TransactionReviewController);

import TransactionTypeToggleController from './transaction_type_toggle_controller';
application.register('transaction-type-toggle', TransactionTypeToggleController);

import TrxformController from './trxform_controller';
application.register('trxform', TrxformController);

import TrxsearchController from './trxsearch_controller';
application.register('trxsearch', TrxsearchController);

import TrxtypeRadioButtonsController from './trxtype_radio_buttons_controller';
application.register('trxtype-radio-buttons', TrxtypeRadioButtonsController);

import TypeaheadController from './typeahead_controller';
application.register('typeahead', TypeaheadController);

import DocumentFormController from './document_form_controller';
application.register('document-form', DocumentFormController);

import BillFormController from './bill_form_controller';
application.register('bill-form', BillFormController);

import SummaryTilesController from './summary_tiles_controller';
application.register('summary-tiles', SummaryTilesController);

import CategorySuggestController from './category_suggest_controller';
application.register('category-suggest', CategorySuggestController);

import ReportsChartController from './reports_chart_controller';
application.register('reports-chart', ReportsChartController);

import SortableHeaderController from './sortable_header_controller';
application.register('sortable-header', SortableHeaderController);

import ClipboardController from './clipboard_controller';
application.register('clipboard', ClipboardController);

import ConfirmDestroyController from './confirm_destroy_controller';
application.register('confirm-destroy', ConfirmDestroyController);

import StatusPollController from './status_poll_controller';
application.register('status-poll', StatusPollController);

import ImportUploadController from './import_upload_controller';
application.register('import-upload', ImportUploadController);
