default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: olubalance_development
  username: <%= ENV['OLUBALANCE_DATABASE_USERNAME'] %>
  password: <%= ENV['OLUBALANCE_DATABASE_PASSWORD'] %>
  host: localhost

test:
  <<: *default
  database: olubalance_test
  username: <%= ENV['OLUBALANCE_DATABASE_USERNAME'] %>
  password: <%= ENV['OLUBALANCE_DATABASE_PASSWORD'] %>
  host: localhost
  
production:
  <<: *default
  database: olubalance_production
  username: <%= ENV['OLUBALANCE_DATABASE_USERNAME'] %>
  password: <%= ENV['OLUBALANCE_DATABASE_PASSWORD'] %>