# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!(email: 'john@gmail.com', password: 'topsecret', password_confirmation: 'topsecret', first_name: 'John', last_name: 'Smith', timezone: 'Eastern Time (US & Canada)')

Account.create!(name: 'PNC',   starting_balance: 50_000, user_id: 1)
Account.create!(name: 'Chase', starting_balance: 1500, user_id: 1)

Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'DLM',                      amount: 132.72,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'American Express payment', amount: 100.00,  account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Mortgage',                 amount: 1237.81, account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'CL Sale',                  amount: 50.00,   account_id: 1, trx_type: 'credit')
Transaction.create!(trx_date: DateTime.current, description: 'Meijer',                   amount: 22.38,   account_id: 1, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Car Payment',              amount: 411.00,  account_id: 1, trx_type: 'debit')

Transaction.create!(trx_date: DateTime.current, description: 'Amazon',                   amount: 50.40,   account_id: 2, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Capital One',              amount: 18.83,   account_id: 2, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Whole Foods',              amount: 48.99,   account_id: 2, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Golden Lamb',              amount: 55.16,   account_id: 2, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'BP Gas',                   amount: 32.44,   account_id: 2, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Sheetz',                   amount: 37.12,   account_id: 2, trx_type: 'debit')
Transaction.create!(trx_date: DateTime.current, description: 'Corner Store',             amount: 10.00,   account_id: 2, trx_type: 'debit')
